version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/airbnb
permissions:
  - object: /home/ubuntu/airbnb
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: /home/ubuntu/deploy.sh
      timeout: 60
      runas: root
